In [1]:
import pandas as pd

In [4]:
data = pd.read_csv(r'C:\Users\Jona\Desktop\tuxff\data\nfl_data\fantasy_data.csv', delimiter=',')
print(len(data))
print(data.columns)
data.head(5)

29369
Index(['Player', 'Tm', 'Pos', 'Age', 'G', 'GS', 'Pass_Cmp', 'Pass_Att',
       'Pass_Yds', 'Pass_TD', 'Pass_Int', 'Rush_Att', 'Rush_Yds', 'Rush_Y/A',
       'Rush_TD', 'Rec_Tgt', 'Rec_Rec', 'Rec_Yds', 'Rec_Y/R', 'Rec_TD', 'Fmb',
       'FmbLost', 'Scrim_TD', 'Key', 'Year', 'Pass_Y/A', 'Scrim_Yds',
       'num_games', 'games_played_pct', 'games_started_pct', 'ProBowl',
       'AllPro', 'Exp', 'Touches', 'Pass_Cmp%', 'Rec_Catch%',
       'Pass_Cmp_per_game', 'Pass_Att_per_game', 'Pass_Yds_per_game',
       'Pass_TD_per_game', 'Pass_Int_per_game', 'Rush_Att_per_game',
       'Rush_Yds_per_game', 'Rush_TD_per_game', 'Rec_Tgt_per_game',
       'Rec_Rec_per_game', 'Rec_Yds_per_game', 'Rec_TD_per_game',
       'Fmb_per_game', 'FmbLost_per_game', 'Scrim_TD_per_game',
       'Scrim_Yds_per_game', 'Touches_per_game', 'Points_half-ppr',
       'PPG_half-ppr', 'PPT_half-ppr', 'PointsOvrRank_half-ppr',
       'PointsPosRank_half-ppr', 'PPGOvrRank_half-ppr', 'PPGPosRank_half-ppr',
       'PPTOvrRank_half-ppr', 'PPTPosRank_half-ppr', 'Points_VORP_half-ppr',
       'PPG_VORP_half-ppr', 'PointsTarget_half-ppr', 'PPGTarget_half-ppr'],
      dtype='object')

,Player,Tm,Pos,Age,G,GS,Pass_Cmp,Pass_Att,Pass_Yds,Pass_TD,...,PointsOvrRank_half-ppr,PointsPosRank_half-ppr,PPGOvrRank_half-ppr,PPGPosRank_half-ppr,PPTOvrRank_half-ppr,PPTPosRank_half-ppr,Points_VORP_half-ppr,PPG_VORP_half-ppr,PointsTarget_half-ppr,PPGTarget_half-ppr
0,Israel Abanikanda,NYJ,RB,21,6,0,0,0,0,0,...,400,99,342,90,462,123,-139.54,-8.425000,NaN,NaN
1,Jared Abbrederis,GNB,WR,25,10,0,0,0,0,0,...,394,152,407,160,214,141,-142.20,-8.858750,1.3,0.260000
2,Jared Abbrederis,GNB,WR,26,5,0,0,0,0,0,...,513,201,501,200,286,182,-154.20,-10.090000,5.9,0.842857
3,Jared Abbrederis,DET,WR,27,7,0,0,0,0,0,...,452,174,438,172,171,109,-132.90,-8.857143,NaN,NaN
4,Ameer Abdullah,DET,RB,22,16,9,0,0,0,0,...,140,42,199,62,412,107,-24.30,-3.518750,24.3,12.150000

In [9]:
data_relevant = data.copy()[['Key', 'Player', 'Pos', 'Tm', 'Year', 'Exp', 'Age', 'num_games', 'G', 'GS', 'Pass_Cmp', 
                             'Pass_Att', 'Pass_Yds', 'Pass_TD', 'Pass_Int', 'Rush_Att', 'Rush_Yds', 'Rush_TD', 'Rec_Tgt', 
                             'Rec_Rec', 'Rec_Yds', 'Rec_TD' ,'Fmb', 'FmbLost', 'ProBowl', 'AllPro', 'Points_half-ppr']]
data_relevant.head()

,Key,Player,Pos,Tm,Year,Exp,Age,num_games,G,GS,...,Rush_TD,Rec_Tgt,Rec_Rec,Rec_Yds,Rec_TD,Fmb,FmbLost,ProBowl,AllPro,Points_half-ppr
0,AbanIs00,Israel Abanikanda,RB,NYJ,2023,0,21,17,6,0,...,0,11.0,7,43,0,1.0,1.0,0,0,12.8
1,AbbrJa00,Jared Abbrederis,WR,GNB,2015,0,25,16,10,0,...,0,16.0,9,111,0,1.0,0.0,0,0,15.6
2,AbbrJa00,Jared Abbrederis,WR,GNB,2016,1,26,16,5,0,...,0,2.0,1,8,0,0.0,0.0,0,0,1.3
3,AbbrJa00,Jared Abbrederis,WR,DET,2017,2,27,16,7,0,...,0,7.0,3,44,0,0.0,0.0,0,0,5.9
4,AbduAm00,Ameer Abdullah,RB,DET,2015,0,22,16,16,9,...,2,38.0,25,183,1,5.0,2.0,0,0,104.5

In [56]:
# Create empty dataframe with key, player, pos and lagged features
features_to_lag = ['Exp', 'num_games', 'G', 'GS', 'Pass_Cmp', 'Pass_Att', 'Pass_Yds', 
                   'Pass_TD', 'Pass_Int', 'Rush_Att', 'Rush_Yds', 'Rush_TD', 'Rec_Tgt', 
                   'Rec_Rec', 'Rec_Yds', 'Rec_TD', 'Fmb', 'FmbLost', 'ProBowl', 'AllPro']

# Create column names
column_names = ['Key', 'Player', 'Pos', 'Year', 'Age']
for feature in features_to_lag:
    for lag in [3, 2, 1]:
        column_names.append(f"{feature}_{lag}")
        
column_names.append('Points_half-ppr')

# Create empty dataframe
data_MDN = pd.DataFrame(columns=column_names)
print(f"Created empty dataframe with {len(column_names)} columns")
print("Columns:", column_names[:7], "...", column_names[-3:])  # Show first 10 columns

Created empty dataframe with 66 columns
Columns: ['Key', 'Player', 'Pos', 'Year', 'Age', 'Exp_3', 'Exp_2'] ... ['AllPro_2', 'AllPro_1', 'Points_half-ppr']

In [58]:
all_rows = []

for idx, row in data_relevant.iterrows():
    player_row = pd.Series(index=column_names, dtype=object)
    
    player_row['Key'] = row['Key']
    player_row['Player'] = row['Player']
    player_row['Pos'] = row['Pos']
    player_row['Year'] = row['Year']
    player_row['Age'] = row['Age']
    player_row['Points_half-ppr'] = row['Points_half-ppr']
    
    years = [1, 2, 3]
    for year in years:
        filtered_data = data_relevant[(data_relevant['Key'] == row['Key']) & (data_relevant['Year'] == row['Year'] - year)]
        if len(filtered_data) > 0:
            row_year = filtered_data.iloc[0]
        else:
            row_year = pd.Series(0, index=row.index)
            row_year['Exp'] = -1
        
        for feature in features_to_lag:
            player_row[f"{feature}_{year}"] = row_year[feature]
    
    all_rows.append(player_row)

data_MDN = pd.DataFrame(all_rows)

In [ ]:
data_MDN = data_MDN[~((data_MDN['Exp_3'] == -1) & 
                      (data_MDN['Exp_2'] == -1) & 
                      (data_MDN['Exp_1'] == -1))]
data_MDN = pd.get_dummies(data_MDN, columns=['Pos'], drop_first=True, dtype=int).reset_index(drop=True)
points_col = data_MDN.pop('Points_half-ppr')
data_MDN['Points_half-ppr'] = points_col

In [ ]:
pd.set_option('display.max_columns', None)
data_MDN.head(5)

,Key,Player,Year,Age,Exp_3,Exp_2,Exp_1,num_games_3,num_games_2,num_games_1,G_3,G_2,G_1,GS_3,GS_2,GS_1,Pass_Cmp_3,Pass_Cmp_2,Pass_Cmp_1,Pass_Att_3,Pass_Att_2,Pass_Att_1,Pass_Yds_3,Pass_Yds_2,Pass_Yds_1,Pass_TD_3,Pass_TD_2,Pass_TD_1,Pass_Int_3,Pass_Int_2,Pass_Int_1,Rush_Att_3,Rush_Att_2,Rush_Att_1,Rush_Yds_3,Rush_Yds_2,Rush_Yds_1,Rush_TD_3,Rush_TD_2,Rush_TD_1,Rec_Tgt_3,Rec_Tgt_2,Rec_Tgt_1,Rec_Rec_3,Rec_Rec_2,Rec_Rec_1,Rec_Yds_3,Rec_Yds_2,Rec_Yds_1,Rec_TD_3,Rec_TD_2,Rec_TD_1,Fmb_3,Fmb_2,Fmb_1,FmbLost_3,FmbLost_2,FmbLost_1,ProBowl_3,ProBowl_2,ProBowl_1,AllPro_3,AllPro_2,AllPro_1,Pos_RB,Pos_TE,Pos_WR,Points_half-ppr
0,AbbrJa00,Jared Abbrederis,2016,26,-1,-1,0,0,0,16,0,0,10,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,16.0,0,0,9,0,0,111,0,0,0,0.0,0.0,1.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,1,1.3
1,AbbrJa00,Jared Abbrederis,2017,27,-1,0,1,0,16,16,0,10,5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,16.0,2.0,0,9,1,0,111,8,0,0,0,0.0,1.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,1,5.9
2,AbduAm00,Ameer Abdullah,2016,23,-1,-1,0,0,0,16,0,0,16,0,0,9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,143,0,0,597,0,0,2,0.0,0.0,38.0,0,0,25,0,0,183,0,0,1,0.0,0.0,5.0,0.0,0.0,2.0,0,0,0,0,0,0,1,0,0,24.3
3,AbduAm00,Ameer Abdullah,2017,24,-1,0,1,0,16,16,0,16,2,0,9,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,143,18,0,597,101,0,2,0,0.0,38.0,5.0,0,25,5,0,183,57,0,1,1,0.0,5.0,0.0,0.0,2.0,0.0,0,0,0,0,0,0,1,0,0,111.9
4,AbduAm00,Ameer Abdullah,2018,25,0,1,2,16,16,16,16,2,14,9,2,11,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,143,18,165,597,101,552,2,0,4,38.0,5.0,35.0,25,5,25,183,57,162,1,1,1,5.0,0.0,2.0,2.0,0.0,1.0,0,0,0,0,0,0,1,0,0,2.4

In [64]:
data_MDN.to_csv(r'C:\Users\Jona\Desktop\tuxff\data\nfl_data\data_mdn.csv', index=False)